/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiProtectedDataRouteImport } from './routes/api/protected/data'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProtectedDataRoute = ApiProtectedDataRouteImport.update({
  id: '/api/protected/data',
  path: '/api/protected/data',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/protected/data': typeof ApiProtectedDataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/protected/data': typeof ApiProtectedDataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/protected/data': typeof ApiProtectedDataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/protected/data'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/protected/data'
  id:
    | '__root__'
    | '/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/protected/data'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiProtectedDataRoute: typeof ApiProtectedDataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protected/data': {
      id: '/api/protected/data'
      path: '/api/protected/data'
      fullPath: '/api/protected/data'
      preLoaderRoute: typeof ApiProtectedDataRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiProtectedDataRoute: ApiProtectedDataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
